#!/usr/bin/bash


echo "Syncing folder: Vaults"
rclone bisync "/home/agardh/Google Drive/Obsidian" "gdrive:Obsidian" --check-access --check-filename .RCLONE_TEST --drive-skip-gdocs

echo "Syncing folder: Musescore"
rclone bisync "/home/agardh/Google Drive/Musik" "gdrive:Musik" --check-access --check-filename .RCLONE_TEST --drive-skip-gdocs

echo "Syncing folder: Lajv"
rclone bisync "/home/agardh/Google Drive/Lajv" "gdrive:Lajv" --check-access --check-filename .RCLONE_TEST --drive-skip-gdocs


echo "Sync done."

sleep 3
